dist: xenial
language: c

stages:
  - test

jobs:
  include:
    - stage: test
      name: gcc
      script: make clean run CC=gcc OPTFLAGS="-O2 -mtune=native"

    - stage: test
      name: clang
      script: make clean run CC=clang OPTFLAGS="-O2 -mtune=native"
